source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BindViewControllerToView_Example', :exclusive => true do
  pod "BindViewControllerToView", :path => "../"
end

target 'BindViewControllerToView_Tests', :exclusive => true do
  pod "BindViewControllerToView", :path => "../"

  
end
